dependencies:
  # organization/repo/version
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1' 


dotenv: .env
networks:
  rinkeby:
    verify: True
  development:
    verify: False
  rinkeby:
    eth_usd_price_feed = '0x52a4B566F4a091Bce9A94ad9c1cAc177A8de65e9'
  ganache-local_real:
    verify: False
  mainnet-fork-james:
    eth_usd_price_feed = '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
  mainnet-fork-james:
    verify: False 
wallets:
  from_key: '${PRIVATE_KEY}'

